const Router = require('express')
const router = new Router()
const userRouter = require('./user.router')
const userAnswerRouter = require('./user_answer.router')
const courseRouter = require('./course.router')
const courseIterationRouter = require('./course_iteration.router')
const courseRegistrationRouter = require('./course_registration.router')
const lessonRouter = require('./lesson.router')
const lessonAnswerRouter = require('./lesson_answer.router')
const lessonQuestionRouter = require('./lesson_question.router')

router.use('/user', userRouter)
router.use('/userAnswer', userAnswerRouter)
router.use('/course', courseRouter)
router.use('/courseIteration', courseIterationRouter)
router.use('/courseRegistration', courseRegistrationRouter)
router.use('/lesson', lessonRouter)
router.use('/lessonAnswer', lessonAnswerRouter)
router.use('/lessonQuestion', lessonQuestionRouter)

module.exports = router
